# Generated by Django 2.2.2 on 2019-07-01 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='')),
                ('file_type', models.CharField(choices=[('IPS', 'Incoming Payment Summary'), ('Other', 'File type not recognized')], default='Other', max_length=40)),
                ('progress', models.IntegerField(default=0)),
                ('validation_status', models.CharField(blank=True, choices=[('NEW', 'New Upload'), ('VP', 'Validation Pending'), ('VIP', 'Validating'), ('VC', 'Validated')], max_length=15, null=True)),
                ('validation_results', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FileUpload',
                'verbose_name_plural': 'FileUpload Details',
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.IntegerField(blank=True, choices=[(0, 'mpesa'), (1, 'creditcard')], null=True)),
                ('payment_source', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.FloatField()),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'PaymentMode',
                'verbose_name_plural': 'Payment Mode Details',
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_reference', models.CharField(max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=20)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('payment_mode', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filecompare.PaymentMode')),
            ],
            options={
                'verbose_name': 'Payment Detail',
                'verbose_name_plural': 'Payment Details',
                'ordering': ['customer_name'],
            },
        ),
        migrations.CreateModel(
            name='File_Validation_Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_diff_rows', models.TextField(blank=True, null=True)),
                ('json_diff_rows', models.TextField(blank=True, null=True)),
                ('invalid_rows', models.TextField(blank=True, null=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='filecompare.FileUpload')),
            ],
            options={
                'verbose_name': 'FileValidation Summary',
                'verbose_name_plural': 'FileValidation Summary Details',
                'ordering': ['date_added'],
            },
        ),
    ]
